### PR TITLE
updated build.sh file

### PR DESCRIPTION
**Pull request by theNerdFromSiliconValley**
1) User-friendly
2) Fixed code signing
3) Better DMG creation, User can save 24.99$

### CODE REVIEW

**Comment by johankool** [comment]
The DMG creation is only for distribution. DropDMG has a prettier result. (The background added in this PR doesn't match the current looks at all btw.) The user doesn't save anything unless he wants to distribute the app, which I am not sure should be encourage over using "our" distribution binary or building from source. (Also, nothing wrong with supporting a small independent software developer.)

**Comment by johankool** [comment]
Actually, the reason I asked users to edit the script to add their team name over letting them enter it is because this isn't just a random name, but it must be exact as in their signing identity. I think now it is unclear that this has to be an exact match for it to work.

**Comment by theNerdFromSiliconValley** [comment]
> The DMG creation is only for distribution. DropDMG has a prettier result. (The background added in this PR doesn't match the current looks at all btw.) The user doesn't save anything unless he wants to distribute the app, which I am not sure should be encouraged over using "our" distribution binary or building from source. (Also, nothing wrong with supporting a small independent software developer.)

Hi Johan Boss, 
The difference between current dmg and old DMG is only the background image. We can change the image at any time. In terms of being pretty DropDMG is doing nothing extra beyond what Apple Design Fundamentals. 

I really want to support every developer I can since I started coding when I was 9 years old, but i think it is not good to force people to buy a Software when we promote free software. It is a major conflict with using a premium software. (We can make dropDMG that optional, but you have to discuss with Francois Boss since free DMG is also good as premium DMG) , DropDMG is good when someone using GUI. In our case, we are just using the command line. So using create-dmg makes more sense

**Comment by theNerdFromSiliconValley** [comment]
> Actually, the reason I asked users to edit the script to add their team name over letting them enter it is because this isn't just a random name, but it must be exact as in their signing identity. I think now it is unclear that this has to be an exact match for it to work.
HI Johan Boss, Good suggestion, we can put that in the text in the Bash script.

**Pull request closed without merging**
